<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    'answer_order_detail_{id}' => 'Вы выбрали заказ #{id}',
    'button_back' => '',
    'button_reject' => '',
    'command_already_registered' => 'Вы уже успешно авторизовались в нашей системе',
    'command_back' => 'Назад',
    'command_contact' => 'Отправить контакт',
    'command_contact_complete' => 'Спасибо, авторизация прошла успешно',
    'command_contact_not_found' => '',
    'command_decline' => 'Отказаться',
    'command_empty' => 'Ничего не найдено',
    'command_hours_created' => '@@Рабочий день успешно начат@@',
    'command_hours_isset' => '@@Вы уже начали рабочий день@@',
    'command_location' => '@@А теперь отправьте свое местоположение, нажав кнопку "Отправить местоположение"@@',
    'command_location_missing' => '@@Вы находитесь слишком далеко от объекта@@',
    'command_order_is_decline' => '',
    'command_order_list' => 'Список доступных заказов, подходящих для вас',
    'command_send_location' => '@@Отправить местоположение@@',
    'command_start' => 'Для продолжения авторизации отправьте свой контакт, пожалуйста',
    'start_day_message' => '@@Внимание! Для того, чтобы отметка о начале рабочего дня появилась в нашей системе, вам необходимо выбрать заказ, к которому собираетесь приступить@@',
];
