<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Nothing to attach!!!' => 'Нечего добавлять к отчету',
    'Select an order for report' => 'Выберите заказ, к которому будет добавлен отчет',
    'View report #{id}' => 'Просмотреть фото-отчет #{id}',
    'button_accept' => 'Принять',
    'button_back' => '⬅ Назад',
    'button_menu' => '⏹ Меню',
    'button_next' => 'Следующий ▶',
    'button_previous' => '◀ Предыдущий',
    'button_reject' => 'Отказаться',
    'button_report_cancel' => 'Отменить отчет',
    'button_report_save' => 'Сохранить отчет',
    'button_report_start' => '📷 Начать фото-отчет',
    'command_accept' => 'Принять заказ',
    'command_accept_failed' => 'При принятии заказа произошли ошибки',
    'command_accept_successfully' => 'Вы успешно приняли заказ',
    'command_already_registered' => 'Вы уже успешно авторизовались в нашей системе',
    'command_back' => 'Назад',
    'command_contact' => 'Отправить контакт',
    'command_contact_complete' => 'Спасибо, авторизация прошла успешно',
    'command_contact_not_found' => 'Контакт не найден',
    'command_coworker_my' => 'Мои работники',
    'command_day_list' => 'Посмотреть статистику',
    'command_decline' => 'Отказаться',
    'command_description_menu' => '',
    'command_description_my' => '',
    'command_description_start_day' => '',
    'command_empty' => 'Ничего не найдено',
    'command_hours_closed' => 'Рабочий день закрыт',
    'command_hours_created' => 'Рабочий день успешно начат',
    'command_hours_error' => '',
    'command_hours_errors' => 'Простите! На сервере произошли какие-то ошибки',
    'command_hours_isset' => 'Рабочий день уже был начат',
    'command_hours_worked_{time}' => 'Приблизительный расчет часов: {time}',
    'command_location_missing' => 'Вы находитесь слишком далеко от рабочего места',
    'command_location_send' => 'Отправить местоположение',
    'command_missing_order_id' => 'Вы не выбрали заказ, по которому хотите начать рабочий день',
    'command_order_is_decline' => '',
    'command_order_list' => 'Список доступных заказов, подходящих для вас',
    'command_orders_list' => '📖 Доступные заказы',
    'command_orders_my' => '🏷 Ваши заказы',
    'command_please_try_later' => '',
    'command_reject_failed' => 'При отказе от заказа произошли ошибки',
    'command_reject_successfully' => 'Вы успешно отказались от заказа',
    'command_send_messages' => 'Отправить уведомления',
    'command_start' => 'Для продолжения авторизации отправьте свой контакт, пожалуйста',
    'command_start_day' => '🕐 Начать рабочий день',
    'command_start_report' => '',
    'command_stop_day' => '🕐 Завершить рабочий день',
    'message_attached_to_report' => 'Сообщение добалено к фото-отчету',
    'message_comment_attached_to_report' => 'Комментарий добавлен к фото-отчету',
    'message_images_attached_to_report' => 'Изображение добавлено к фото-отчету',
    'message_menu' => 'Здравствуйте!
Это основное меню телеграм бота',
    'message_report_cancelled' => 'Создание фото-отсета отменено',
    'message_report_{id}_attached_to_{order_id}' => 'Фото-отчет #{id} прикреплен к заказу {order_id}',
    'message_report_{id}_saved' => 'Фото-отчет #{id} сохранен. Выберите заказ, к которому будет прикреплен текущий фото-отчет',
    'message_start_report' => 'Начат фото-отчет. Отправьте файлы, которые будут использованы в отчете',
    'message_text_or_image_and_save' => 'Отправьте изображение или текст и нажмите кнопку "Сохранить отчет"',
    'send a comment for order #{id}' => '',
];
