<?php

namespace app\controllers;

use app\models\Category;
use app\models\Coworker;
use app\models\Hours;
use app\models\Order;
use app\models\Report;
use app\models\Requirement;
use app\models\User;
use Yii;
use yii\bootstrap5\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\UploadedFile;

class OrderController extends BaseController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'view', 'delete', 'coworker', 'material', 'get-list'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'delete', 'coworker', 'material'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['list'],
                        'roles' => ['?']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ]
            ]
        ]);
    }

    public function beforeAction($action)
    {
        if ($action->id == 'coworker') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new \app\models\search\OrderSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        $model = Order::findOne($id);

        if (\Yii::$app->request->isAjax) {
            return $this->renderAjax('view', [
                'model' => $model,
            ]);
        }

        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function actionDelete($id)
    {
        $model = Order::findOne($id);
        $model->unlinkAll('attachments', true);
        $model->delete();
        return $this->redirect(['/order/index']);
    }

    public function actionCoworker($id = null)
    {
        if ($id) {
            $model = Order::findOne($id);
            $this->view->title = \Yii::t('app', 'Update Order #{id}', ['id' => $id]);
        } else {
            $model = new Order();
            $this->view->title = \Yii::t('app', 'Order coworker');
        }

        if (\Yii::$app->request->isPost) {
            $uploadedFiles = UploadedFile::getInstances($model, 'files');
            if ($model->load(\Yii::$app->request->post()) && $model->save()) {
                $model->files = $uploadedFiles;
                $model->setAttachments($uploadedFiles);
                $result = $model->sendAndUpdateTelegramNotifications();
                \Yii::$app->session->setFlash('success', \Yii::t('app', 'Order is successfully saved'));
                return $this->redirect('index');
            } else {
                \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Order is not saved'));
                \Yii::error($model->getErrors());
                \Yii::error($model->attributes);
            }
        }

        return $this->render('coworker', [
            'model' => $model
        ]);
    }

    /**
     * Действие для AJAX валидации формы заказа
     */
    public function actionValidate()
    {
        $model = new Order();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        return $this->redirect(['index']);
    }

    public function actionMaterial()
    {
        $model = new Order();
        return $this->render('material', [
            'model' => $model
        ]);
    }

    public function actionDetail($id)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($id) {
            $model = Order::findOne($id);
            if (\Yii::$app->user->isGuest) {
                return ["ok" => false, "message" => "Unknown user"];
            }
            return ["ok" => true, "data" => $model->getDetails()];
        }
        return [];
    }

    public function actionResendInvite($id)
    {
        $model = Order::findOne($id);
        $result = $model->sendAndUpdateTelegramNotifications();
//        \Yii::error( $result );
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionResendNotify($id)
    {
        $model = Order::findOne($id);
        $result = $model->sendAndUpdateTelegramNotifications();
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionReport($id)
    {
        $report = new Report();
        $order = Order::findOne($id);
        if (\Yii::$app->request->isPost) {
            $report->load(\Yii::$app->request->post());
            $report->files = UploadedFile::getInstances($report, 'files');
            if ($report->validate() && $report->upload()) {
                \Yii::$app->session->setFlash('success', \Yii::t('app', 'Report is successfully saved'));
                return $this->redirect(['view', 'id' => $id]);
            } else {
                \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Report is not saved'));
                \Yii::error($report->getErrors());
            }
        }
        return $this->render('report', [
            'order' => $order,
            'model' => $report
        ]);
    }

    public function actionDeleteReport($id)
    {
        $report = Report::findOne($id);
        foreach ($report->attachments as $attachment) {
            $report->unlink('attachments', $attachment, true);
        }
        $report->delete();
        return $this->redirect(['view', 'id' => $report->order_id]);
    }

    public function actionList()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $user = User::findOne(\Yii::$app->user->id);

        // Находим заказы, в которых есть сотрудники с referrer_id = $user->id
        $orders = Order::find()
            ->joinWith('coworkers')
            ->where(['coworker.referrer_id' => $user->id])
            ->all();

        $hours = Hours::find()
            ->joinWith('order')
            ->where(['order.id' => ArrayHelper::getColumn($orders, 'id')])
            ->all();

        return $hours;
    }

    public function actionCreateRequirement($id = null, $index = null)
    {
        $itemData = [
            'category_id' => \Yii::$app->request->get('category_id'),
            'count' => \Yii::$app->request->get('count'),
            'property_id' => \Yii::$app->request->get('property_id'),
            'type' => \Yii::$app->request->get('type'),
            'value' => \Yii::$app->request->get('value'),
            'dimension_id' => \Yii::$app->request->get('dimension_id'),
        ];

        // Фильтруем пустые значения
        $itemData = array_filter($itemData, function($value) {
            return $value !== null && $value !== '';
        });

        return $this->renderAjax('_requirements', [
            'item' => $itemData,
        ]);
    }

    public function actionSetPayed()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post = \Yii::$app->request->post();
        $model = Order::findOne($post['id']);
        $model->is_payed = $post['is_payed'];
        return ['ok' =>$model->save()];
    }
}
