<?php

namespace app\controllers;

use app\models\Order;
use app\models\Report;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\UploadedFile;

class OrderController extends BaseController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'view', 'delete', 'coworker', 'material', 'get-list'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'delete', 'coworker', 'material'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['get-list'],
                        'roles' => ['?']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ]
            ]
        ]);
    }

    public function beforeAction($action)
    {
        if ($action->id == 'coworker') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new \app\models\search\OrderSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        $model = Order::findOne($id);

        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function actionDelete($id)
    {
        $model = Order::findOne($id);
        $model->unlinkAll('attachments', true);
        $model->delete();
        return $this->redirect(['/order/index']);
    }

    public function actionCoworker($id = null)
    {
        if ($id) {
            $model = Order::findOne($id);
            $this->view->title = \Yii::t('app', 'Update Order #{id}', ['id' => $id]);
        } else {
            $model = new Order();
            $this->view->title = \Yii::t('app', 'Order coworker');
        }

        if (\Yii::$app->request->isPost) {
            $uploadedFiles = UploadedFile::getInstances($model, 'files');
            if ($model->load(\Yii::$app->request->post()) && $model->save()) {
                $model->files = $uploadedFiles;
                $model->setAttachments($uploadedFiles);
                $result = $model->sendAndUpdateTelegramNotifications();
                \Yii::$app->session->setFlash('success', \Yii::t('app', 'Order is successfully saved'));
                return $this->redirect('index');
            } else {
                \Yii::error($model->errors);
                \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Order is not saved'));
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('coworker', [
            'model' => $model
        ]);
    }

    public function actionMaterial()
    {
        $model = new Order();
        return $this->render('material', [
            'model' => $model
        ]);
    }

    public function actionDetail($id)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($id) {
            $model = Order::findOne($id);
            if (\Yii::$app->user->isGuest) {
                return ["ok" => false, "message" => "Unknown user"];
            }
            return ["ok" => true, "data" => $model->getDetails()];
        }
        return [];
    }

    public function actionResendInvite($id)
    {
        $model = Order::findOne($id);
        $result = $model->sendAndUpdateTelegramNotifications();
//        \Yii::error( $result );
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionResendNotify($id)
    {
        $model = Order::findOne($id);
        $result = $model->sendAndUpdateTelegramNotifications();
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionReport($id)
    {
        $report = new Report();
        $order = Order::findOne($id);
        if (\Yii::$app->request->isPost) {
            $report->load(\Yii::$app->request->post());
            $report->files = UploadedFile::getInstances($report, 'files');
            if ($report->validate() && $report->upload()) {
                \Yii::$app->session->setFlash('success', \Yii::t('app', 'Report is successfully saved'));
                return $this->redirect(['view', 'id' => $id]);
            } else {
                \Yii::$app->session->setFlash('danger', \Yii::t('app', 'Report is not saved'));
                \Yii::error($report->getErrors());
            }
        }
        return $this->render('report', [
            'order' => $order,
            'model' => $report
        ]);
    }

    public function actionDeleteReport($id)
    {
        $report = Report::findOne($id);
        foreach ($report->attachments as $attachment) {
            $report->unlink('attachments', $attachment, true);
        }
        $report->delete();
        return $this->redirect(['view', 'id' => $report->order_id]);
    }
}
