<?php

namespace app\components\telegram;

use aki\telegram\base\Command;

class StartCommand extends Command
{
    public static function run($command, callable $fun)
    {
        return parent::run($command, $fun); // TODO: Change the autogenerated stub
    }
}